name: tectosaur2
channels:
  - conda-forge
dependencies:
  - clangxx
  - pre-commit
  - jupyterlab
  - cython
  - numpy
  - scipy
  - matplotlib
  - sympy
  - mamba
  - pip
  - pyproj
  # - gdal
  - gmsh
  # - pycuda
  - k3d
  - black
  - jupyter-book
  - psutil
  - pandas
  - line_profiler
  - boto3
  - ipdb
  - jupyterlab_code_formatter
  - quadpy
  - jupyterlab-lsp
  - python-lsp-server
  - ipympl
  - cutde
  - pip:
    - jupyter-book >= 0.11
    - pygmsh<7
    - sphinxcontrib-bibtex >= 2.2.0
    - sphinx-sitemap
    - loopy
    - boxtree
    # - okada_wrapper
    - tanh-sinh
