name: bie_book
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - cython
  - numpy
  - scipy
  - matplotlib
  - sympy
  - mamba
  - pip
  - pyproj
  - gdal
  - gmsh
  # - pycuda
  - k3d
  - black
  - jupyter-book
  - pyopencl
  - psutil
  - pandas
  - line_profiler
  - boto3
  - ipdb
  - pip:
    - jupyter-book >= 0.11
    - cutde #might want a development version!
    - pygmsh<7
    - sphinxcontrib-bibtex >= 2.2.0
    - sphinx-sitemap
    - loopy
    - boxtree
    - okada_wrapper
