name: bie_book
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - sympy
  - mamba
  - pip
  - pyproj
  - gdal
  - gmsh
  # - pycuda
  - k3d
  - black
  - jupyter-book
  - pyopencl
  - psutil
  - pandas
  - pip:
    - cutde
    - pygmsh
    - sphinxcontrib-bibtex >= 2.2.0
    - loopy
    - boxtree
