name: tectosaur2
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - sympy
  - pandas

  - quadpy
  - psutil
  - pytest
  - pre-commit
  - black
  - line_profiler

  - cython
  - cxx-compiler
  - mamba
  - pip

  - cutde
  - boto3
  - pyproj
  - gmsh
  - k3d
  # - pycuda
  # - gdal

  - jupyter-book
  - pip:
    - pygmsh<7
    - sphinxcontrib-bibtex >= 2.2.0
    - sphinx-sitemap
