name: bie_notebooks
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - sympy
  - mamba
  - pip
  - pyproj
  - gdal
  - gmsh
  - pycuda
  - k3d
  - black
  - pip:
    - cutde
    - pygmsh
